#define TECHWEB_POINTS_1_MINUTE (60 * TECHWEB_SINGLE_SERVER_INCOME)
#define TECHWEB_POINTS_5_MINUTES (5 * TECHWEB_POINTS_1_MINUTE)
#define TECHWEB_POINTS_10_MINUTES (10 * TECHWEB_POINTS_1_MINUTE)
#define TECHWEB_POINTS_15_MINUTES (15 * TECHWEB_POINTS_1_MINUTE)
#define TECHWEB_POINTS_30_MINUTES (30 * TECHWEB_POINTS_1_MINUTE)
#define TECHWEB_POINTS_1_HOUR (60 * TECHWEB_POINTS_1_MINUTE)

#define TECHWEB_TIER_QUANTUM_POINTS TECHWEB_POINTS_1_HOUR
